//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scaffold.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class Products_
    {
        public System.Guid ProductId { get; set; }

		/* show user something more meaningful
		 other than name of property, a data annotation
		 This shows "Product name" on all routes
		*/
		[Display(Name ="Product name")]
        public string Name { get; set; }

        public decimal Price { get; set; }
    }
}
